In [1]:
import numpy as np

In [17]:
x = -2.69

6.31

In [24]:
np.log10(500)

2.6989700043360187

In [30]:
pIC50 = nm_log_to_pm_log(-2.69)

-2.6900000000000004

In [41]:
np.log10(500)

2.6989700043360187

In [22]:
import torch

# 假设您的 batch 是一个形状为 (batch_size, vector_length) 的张量
batch = torch.tensor([[1, 0, 1], [0, 1, 1], [1, 1, 0]])

# 在第一维上使用广播，对 batch 中的向量执行按位 AND 运算
result1 = torch.bitwise_and(batch.unsqueeze(1), batch.unsqueeze(0))
C = result1.sum(-1)
result2 = torch.add(batch.unsqueeze(1), batch.unsqueeze(0))
A_B = result2.sum(-1)
result2_sum = torch.bitwise_or(batch.unsqueeze(1), batch.unsqueeze(0)).sum(-1)
# 将 result 对角线上的元素全部设为 0，以避免将向量与自己相与
#result = torch.where(torch.eye(result.shape[0], device=result.device, dtype=torch.bool), 
#                     torch.zeros_like(result), result)
result = C / (A_B-C+1e-5)
print(result)
m1=result>0.5
m2=result<0.5
m = torch.logical_and(m1.unsqueeze(1),m2.unsqueeze(2))
print(m,m.shape)

tensor([[1.0000, 0.3333, 0.3333],
        [0.3333, 1.0000, 0.3333],
        [0.3333, 0.3333, 1.0000]])
tensor([[[False, False, False],
         [ True, False, False],
         [ True, False, False]],

        [[False,  True, False],
         [False, False, False],
         [False,  True, False]],

        [[False, False,  True],
         [False, False,  True],
         [False, False, False]]]) torch.Size([3, 3, 3])


In [3]:
result = torch.where(torch.eye(result.shape[0], device=result.device, dtype=torch.bool), 
                   torch.zeros_like(result), result)
result

tensor([[[0, 0, 1],
         [0, 0, 1],
         [1, 0, 0]],

        [[0, 0, 1],
         [0, 0, 1],
         [0, 1, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [1, 1, 0]]])

In [17]:
from rdkit import Chem
from rdkit.Chem import AllChem
import numpy as np
import torch
def generate_morgan_fingerprint(mol, radius=2, nBits=2048):
    """
    生成分子的Morgan指纹

    :param mol: 分子
    :param radius: 搜索半径，默认为2
    :param nBits: 指纹的长度，默认为2048
    :return: 分子的Morgan指纹
    """
    fp = AllChem.GetMorganFingerprintAsBitVect(mol, radius, nBits)
    arr = np.zeros((1,))
    print(arr)
    # Convert the RDKit explicit-valence-bit-vector into a numpy array.
    AllChem.DataStructs.ConvertToNumpyArray(fp, arr)
    return arr

# 示例
smiles = 'CC(=O)OC1=CC=CC=C1C(=O)O'
mol = Chem.MolFromSmiles(smiles)
fp = torch.tensor(generate_morgan_fingerprint(mol),dtype=torch.int)
print(fp)

[0.]
tensor([0, 0, 0,  ..., 0, 0, 0], dtype=torch.int32)
